### ISSUE TITLE
This method does not apply to other software

### ISSUE THREAD

**Issue by newstudent007** [vyrus001/go-mimikatz#3]
This method is successful for mimikatz32.exe.
but,I use the same steps，create go-calc32.exe.
Not available

**Comment by newstudent007** [comment]
此方法对mimikatz32.exe成功。
但是，我使用相同的步骤，创建go-calc32.exe。
无法使用 @vyrus001

**Comment by newstudent007** [comment]
This method is successful for mimikatz32.exe.
but,I use the same steps，create go-calc32.exe.
Not available @vyrus001

**Comment by vyrus001** [comment]
the binary is now hardcoded into the logic but the method totally works on other apps now
