### ISSUE TITLE
Cannot run on win2008r2 and win7

### ISSUE THREAD

**Issue by lz520520** [vyrus001/go-mimikatz#4]
The test runs normally above win2012, but the lower version cannot run, I don’t know if the author has tested it

**Comment by vyrus001** [comment]
I have not, ill have to get a hold of an edge vm and debug where the failure is, are you sure the issue is in the packer and not the mimikatz version?

**Comment by vyrus001** [comment]
with the new format, this should be addressed, feel free to re-open if it fails again
