### ISSUE TITLE
[issue] I have some problems and would like to consult you.

### ISSUE THREAD

**Issue by zer0yu** [vyrus001/go-mimikatz#6]
The first:
Perhaps the output location should be specified?
```
go run packer/packer.go -o stub
```

The second:
I have a problem and don't know how to modify it properly
```
❯ go build -o stub/stub github.com/vyrus001/go-mimikatz/stub
# github.com/vyrus001/go-mimikatz/stub
stub/stub.go:15:17: too many arguments in call to syscall.Syscall
	have (uintptr, number, number, number)
	want (uintptr, uintptr, uintptr, uintptr)
note: module requires Go 1.17
```
I hope you can give me some guidance, thank you very much!

**Comment by ryd** [comment]
@zer0yu I got the same message building on MacOS - building on windows works fine again which makes sense.

**Comment by zer0yu** [comment]
@ryd  thx, building on windows works fine
